travis:
  secure:
    BINSTAR_TOKEN: ISWVZE5o7IPWEmYJARNQYEN2ShPgg9lWwTZu6LgSnqa4ah4QvTLPxnLvrCSwnswLjNhlomIGGaPfDHf98mQDLEGKgHlg8DcZuAglnk5GZgA9ZaSHAV/64A+Jd9AVkyphYY769/Cj/Gf2mGgyamyPVTKkWKOSeQXkHF6jhAaTFZ55srWvZv6tF1D5gfwImzck28OW7KxNNbUwIriebkBjTwGGricJBnlackcondHiuFOHGJ0NDvTtiM/+s8hGcDCQ1iold5VnxkSVHJEuBxczunsvRFqcOoucjtLQWW6Y2P+ZPuR8sXgZJfgHo6vaK6mnBTDQrXXZDmsqCFAN9Lgzle05IOOPJJNyHvyAo6I0mnxPyvNjVw0oBmAi6e4FNcIYkHk9vvVm5RieTgA7Ac7Q9VspnqQW/62hh/TzGAsYf//Fba8RgMUyUsq1x/KLCGnl66ImwJk9sCtl1iHS/WvLWKEvoMJBJb0suh1h/vaJUt3G7ZbK8fnBPgPqXPFpiQ1Io/edJCG97geRxPQNh2bHD7i9L++7lex9uDZ4SEVnBw0y/ct2hLjKNp8wrRt2SNhna50dqL8r2ZFd/ANBZ7beKFo6IV95B433Uqee9aY5JtT0FMIxbob3zHebmvGUrmY7oxOXn8DeIXVg7Roq99/jT2QATrePr0c+GLi/ufe9vP8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
